name: live_states_example
description: Demonstrates how to use the flutter_live_states package.
publish_to: 'none'

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  live_states:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
