name: live_states
description: A high-performance, lightweight MVVM state management framework for Flutter with automatic dependency tracking via Zones.
version: 1.1.0
repository: https://github.com/bu-xue/live_states
issue_tracker: https://github.com/bu-xue/live_states/issues
homepage: https://github.com/bu-xue/live_states

topics:
  - state-management
  - mvvm
  - viewmodel
  - livedata
  - reactive

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1
  meta: ^1.16.0
  collection: ^1.19.1

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
